### ISSUE TITLE
clone-leeroy fails when `git` installed to nonstandard location on Windows

### ISSUE THREAD

**Issue by jacobcarpenter** [bgrainger/clone-leeroy#4]
The current version of the script relies on Git for Windows being installed in the standard install location: https://github.com/bgrainger/clone-leeroy/blob/master/src/index.js#L8-L9

While setting up a new machine with a non-standard Git installation path, clone-leeroy fails with 

```
Error: Processing ThirdPartyBinaries/SQLite
  Directory SQLite does not exist; cloning it.
  Command failed: "C:\Program Files (x86)\Git\bin\git.exe" clone --recursive --branch 3.12.1 git@git:ThirdPartyBinaries/SQLite.git
  The system cannot find the path specified.
```

However, it appears that if we remove the special handling for `darwin` and just do `Promise.resolve('git')`, `clone-leeroy` seems to resolve `git` from the `PATH` just fine.

Do you recall the reasons for providing a path-qualified name for `git` on Windows, and do you have any objections to removing it?

**Comment by bgrainger** [comment]
I think maybe git typically didn't add itself to `%PATH%` on Windows three years ago? If it works by default now, I see no need to keep the old code.
